language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

variables:
  PIP_CACHE_DIR: .pipenv/pipcache
  WORKON_HOME: .pipenv/venvs

cache:
  key: pipenv
  paths:
    - .pipenv

install:
  - pipenv sync --dev
  - pipenv run python setup.py install

script:
  - lki
