version: '3'

services:
  zeus:
    container_name: zeus
    hostname: zeus
    image: docker-outer.zaihui.com.cn/inf/common/zeus:latest
    restart: always

    environment:
      - NAME=suziyue
    ports:
      - 1080:1080
      - 1082:1082
    volumes:
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ~/.ssh/royal:/root/.ssh/royal
      - ~/.ssh/holy:/root/.ssh/holy
      - ~/.kube/:/root/.kube/
      - ~/code/src:/src
