#!/usr/bin/env bash
# start a new hugo blog

set -e

if [[ $# -lt 1 ]]; then
  echo "usage: newblog <some blog name>"
  exit 1
fi

NAME=$1
FILENAME="content/cn/posts/`date '+%Y-%m-%d'`-$1.md"

hugo new ${FILENAME}
