#!/usr/bin/env bash
# update docker image in 4 gitlab runners

set -e

if [ ! $# -eq 1 ]; then
    echo "usage: rpdate <image>"
    exit 1
fi

for i in `seq 1 4`;
do
    gsh gitlab-runner-$i docker pull $1;
done
