#!/usr/bin/env bash

set -e

scoop install git

scoop bucket add extras
scoop bucket add nerd-fonts
scoop bucket add ackerr https://github.com/Ackerr/scoop-bucket
scoop bucket add dodorz https://github.com/dodorz/scoop-bucket
scoop bucket add iszy https://github.com/ZvonimirSun/scoop-iszy

scoop install 7zip
scoop install ag
scoop install dig
scoop install docker-compose
scoop install eksctl
scoop install firacode
scoop install fzf
scoop install gcc
scoop install go
scoop install helm
scoop install hugo
scoop install k9s
scoop install kubectl
scoop install kustomize
scoop install lab
scoop install make
scoop install protobuf
scoop install ripgrep
scoop install robo3t
scoop install skaffold
scoop install starship
scoop install stern
scoop install telegram
scoop install vim-nightly
scoop install wget
scoop install windows-terminal
scoop install yarn

scoop install nodejs@14.15.1
scoop hold nodejs
