#!/bin/sh
# a simple wget replacement for MAC OS

set -e

if [ $# -lt 1 ]; then
    echo "usage: wget <source> [<dest>]"
    exit 1
fi

SRC=$1
DEST=$2
if [ -z ${DEST} ]; then
    DEST=${SRC##*/}
fi
echo "Getting ${SRC} to ${DEST}"
curl -s ${SRC} > ${DEST}
